"""
pdf_export.py — PDF Generation Helper for AI Study Planner
Uses fpdf2 to generate beautifully formatted PDF planners.
"""

from datetime import date
from io import BytesIO
from fpdf import FPDF
from utils.validators import days_remaining


def clean_text(text: str) -> str:
    """
    Clean text to make it compatible with Helvetica font (Latin-1).
    Replaces common emojis and Unicode characters to avoid UnicodeEncodeErrors.
    """
    replacements = {
        "📚": "Study: ",
        "🎓": "Exam: ",
        "🔄": "Recovery: ",
        "⏱️": "Time: ",
        "📊": "Avg: ",
        "📅": "Date: ",
        "✏️": "Plan: ",
        "💡": "Tip: ",
        "🌟": "* ",
        "🧠": "* ",
        "⏰": "* ",
        "💤": "* ",
        "🎯": "* ",
        "📵": "* ",
        "🚶": "* ",
        "📝": "* ",
        "🥗": "* ",
        "🔁": "* ",
        "🏆": "* ",
        "🌊": "* ",
        "🦉": "* ",
        "🐢": "* ",
        "🔥": "* ",
        "💪": "* ",
        "✨": "* ",
        "🤝": "* ",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    
    # Convert special single quotes or double quotes to standard ones
    text = text.replace("—", "-").replace("–", "-").replace("’", "'").replace("‘", "'")
    text = text.replace("“", '"').replace("”", '"')
    
    # Encode to Latin-1, replacing unsupported chars with '?'
    return text.encode("latin-1", errors="replace").decode("latin-1")


class StudyPlanPDF(FPDF):
    """Custom FPDF subclass for AI Study Planner reports."""
    
    def __init__(self, style: str, exam_date_str: str, daily_hours: float, days_left: int):
        super().__init__()
        self.style = style
        self.exam_date_str = exam_date_str
        self.daily_hours = daily_hours
        self.days_left = days_left

    def header(self):
        # We only want headers on page 2 and onwards
        if self.page_no() == 1:
            return
            
        # Draw standard secondary page header
        self.set_fill_color(108, 99, 255)  # Primary Brand Color (#6C63FF)
        self.rect(0, 0, 210, 12, 'F')
        
        self.set_y(3)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 9)
        self.cell(95, 5, f"AI STUDY PLANNER  |  Style: {self.style}", align="L")
        self.cell(95, 5, f"Exam: {self.exam_date_str}  |  Days Left: {self.days_left}", align="R")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        
        # Draw a thin divider line above footer
        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.2)
        self.line(10, 282, 200, 282)
        
        self.cell(95, 10, f"Page {self.page_no()}/{{nb}}  -  Generated by AI Study Planner", align="L")
        self.cell(95, 10, "Stay focused and you've got this! ", align="R")


def generate_pdf_bytes(
    subjects: list[str],
    difficulties: dict[str, int],
    exam_date: date,
    daily_hours: float,
    style: str,
    include_recovery: bool,
    include_tips: bool,
    schedule: list[dict],
    allocation: dict[str, float],
    topics: dict[str, list[str]] | None = None,
) -> bytes:
    """
    Build and compile a beautifully styled PDF study plan report.
    Returns the raw PDF bytes ready for st.download_button.
    """
    days_left = days_remaining(exam_date)
    exam_date_str = exam_date.strftime('%d %B %Y')
    
    # Initialize document
    pdf = StudyPlanPDF(style, exam_date_str, daily_hours, days_left)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # ── FIRST PAGE HEADER / COVER ─────────────────────────────────────────────
    
    # Custom colored header box
    pdf.set_fill_color(108, 99, 255)  # #6C63FF
    pdf.rect(0, 0, 210, 45, 'F')
    
    pdf.set_y(12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 10, "AI STUDY PLANNER", align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(200, 245, 245)  # Teal accent
    pdf.cell(0, 6, "Your Personalised Smart Study Guide", align="C", new_x="LMARGIN", new_y="NEXT")
    
    # Content block
    pdf.set_y(52)
    pdf.set_text_color(30, 30, 40)
    
    # Plan parameters cards (2x2 grid in boxes)
    pdf.set_draw_color(210, 210, 255)
    pdf.set_line_width(0.3)
    
    # Row 1
    pdf.set_fill_color(248, 248, 255)
    pdf.rect(10, 52, 92, 18, 'FD')
    pdf.set_xy(14, 54)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 4, "EXAM DATE", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, exam_date_str, new_x="LMARGIN", new_y="NEXT")
    
    pdf.rect(108, 52, 92, 18, 'FD')
    pdf.set_xy(112, 54)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 4, "DAYS REMAINING", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(112)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, f"{days_left} Days Left", new_x="LMARGIN", new_y="NEXT")
    
    # Row 2
    pdf.rect(10, 75, 92, 18, 'FD')
    pdf.set_xy(14, 77)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 4, "DAILY STUDY TARGET", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, f"{daily_hours} Hours / Day", new_x="LMARGIN", new_y="NEXT")
    
    pdf.rect(108, 75, 92, 18, 'FD')
    pdf.set_xy(112, 77)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 4, "STUDY PACING PROFILE", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(112)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, f"{style} Style", new_x="LMARGIN", new_y="NEXT")
    
    # ── SUBJECTS TABLE ────────────────────────────────────────────────────────
    pdf.set_y(102)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, "Subject Weighting & Hour Distribution", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    
    # Headers
    pdf.set_fill_color(108, 99, 255)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(85, 8, " Subject", border=1, fill=True, align="L")
    pdf.cell(45, 8, "Difficulty", border=1, fill=True, align="C")
    pdf.cell(60, 8, "Allocated Study Hours", border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    
    # Body rows
    pdf.set_text_color(30, 30, 40)
    pdf.set_font("Helvetica", "", 10)
    
    alternating = False
    for subj in subjects:
        if alternating:
            pdf.set_fill_color(248, 248, 255)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        diff_val = difficulties.get(subj, 3)
        stars = "*" * diff_val + " " * (5 - diff_val)
        diff_str = f"{diff_val}/5 ({stars})"
        
        pdf.cell(85, 8, f" {clean_text(subj)}", border=1, fill=True, align="L")
        pdf.cell(45, 8, clean_text(diff_str), border=1, fill=True, align="C")
        pdf.cell(60, 8, f"{allocation.get(subj, 0.0)} hrs", border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
        alternating = not alternating
        
    # ── DAILY SCHEDULE ────────────────────────────────────────────────────────
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 6, "Daily Study Schedule", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    
    # Loop over days
    for day in schedule:
        # Check for page overflows (leave 35mm headroom)
        if pdf.get_y() > 245:
            pdf.add_page()
            
        is_exam = day.get("is_exam_day", False)
        is_recovery = day.get("is_recovery", False)
        
        # Color palettes for headers
        if is_exam:
            pdf.set_fill_color(255, 235, 235)  # Light Red
            pdf.set_text_color(180, 40, 40)    # Red text
            pdf.set_draw_color(255, 180, 180)
            day_header_text = f"  EXAM DAY  -  {day['day_label']}"
        elif is_recovery:
            pdf.set_fill_color(235, 253, 253)  # Light Teal
            pdf.set_text_color(20, 120, 120)   # Teal text
            pdf.set_draw_color(180, 230, 230)
            day_header_text = f"  Day {day['day_number']}  -  {day['day_label']} (Recovery & Buffer Day)"
        else:
            pdf.set_fill_color(248, 248, 255)  # Very light purple
            pdf.set_text_color(60, 50, 150)    # Purple text
            pdf.set_draw_color(210, 210, 255)
            day_header_text = f"  Day {day['day_number']}  -  {day['day_label']}  ({day['hours']} hrs)"
            
        pdf.set_font("Helvetica", "B", 10)
        # Draw day header bar
        pdf.cell(0, 7, clean_text(day_header_text), border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
        
        # Day tasks list (with checklist box formatting)
        pdf.set_text_color(50, 50, 60)
        pdf.set_font("Helvetica", "", 9.5)
        pdf.ln(1)
        
        if is_recovery:
            pdf.set_x(15)
            pdf.cell(0, 5.5, "[ ] Consolidate notes and take a light review session", new_x="LMARGIN", new_y="NEXT")
        else:
            for task in day.get("tasks", []):
                subj_name = task["subject"]
                dur = task["duration_min"]
                topic_str = f" ({task['topic']})" if task.get("topic") else ""
                task_line = f"[ ] {subj_name}{topic_str}  -  {dur} min"
                
                # Wrapped tasks are safe in PDF
                pdf.set_x(15)
                pdf.multi_cell(180, 5.5, clean_text(task_line), new_x="LMARGIN", new_y="NEXT")
                
        # Margin space
        pdf.ln(3)
        
    # ── TIPS SECTION ──────────────────────────────────────────────────────────
    if include_tips:
        from utils.prompt_builder import MOTIVATIONAL_TIPS
        
        # Check space
        if pdf.get_y() > 220:
            pdf.add_page()
            
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(108, 99, 255)
        pdf.cell(0, 6, "Useful Study & Focus Tips", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 70)
        
        for tip in MOTIVATIONAL_TIPS[:8]:  # Limit to a selection of 8 tips
            pdf.set_x(12)
            pdf.multi_cell(185, 5, clean_text(f"- {tip}"), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    # Return PDF representation
    output_stream = BytesIO()
    pdf.output(output_stream)
    return output_stream.getvalue()
